architect:
  - h1alexbel
merge:
  script: |
    <merge script>
release:
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9_]+)?$ ]] || exit -1
    <set version>
    git commit -am "${tag}"
    <release to PyPI>
deploy:
  script: |
    echo "There is no such thing as #deploy"
    exit -1
